### ISSUE TITLE
Kann mal jemand die ballgreen.png in ne richtige *.png umwandeln?

### ISSUE THREAD

**Issue by ghost** [Taikaschi/PCM_214#1]
file ballgreen.png 

> ballgreen.png: JPEG image data, JFIF standard 1.01, resolution (DPI), density 0x0, segment length 16, baseline, precision 8, 20x22, frames 3    

file ballred.png 

> ballred.png: PNG image data, 20 x 22, 4-bit colormap, non-interlaced      

file ballorange.png 

> ballorange.png: PNG image data, 20 x 22, 4-bit colormap, non-interlaced

Nicht wirklich ein Issue, per se, ich wollte nur mal das issues-feature von github ausprobieren, aber wenn mal jemand Zeit hat.... :)

**Comment by desto-git** [comment]
https://github.com/Taikaschi/PCM_214/commit/5d23c1d7343b4459b1be362ad76a1e6be82cb072
